### ISSUE TITLE
Sketch 3: sublayers of hidden layers export as empty PNGs

### ISSUE THREAD

**Issue by kopurando** [koenbok/Framer#105]
Hello,
framer.js import feature is a bomb, 
I came accross a little bug however: whenever I import hidden layers with sublayers (subgroups), these subgroups will render as an empty PNG. 

See attachments for better explanation.

Layer structure:
![sketch3_hidden_layers_bug](https://cloud.githubusercontent.com/assets/6130979/3906316/e98dd9be-22f1-11e4-96b3-eef2fda73f4e.png)

Export result:
Hidden layer: 
![rectangle_1-41d3878a-e86c-4ca2-a130-65ad28db707a](https://cloud.githubusercontent.com/assets/6130979/3906314/e30b661a-22f1-11e4-9909-d289abd76455.png)
Sublayer:
![oval_1__456-60f5cd0b-5b2c-4e83-817c-7815887dac00](https://cloud.githubusercontent.com/assets/6130979/3906313/e2faa5f0-22f1-11e4-9bf2-4396ed6e1016.png)
(empty :)

framer studio 1.5.8.(372)
Sketch 3.0.4 (8156)
Sample sketch: https://dl.dropboxusercontent.com/u/3635046/hidden_sublayer_bug.sketch.zip
Sorry if it has been reported before. 

Keep up the great job!

**Comment by dcalhoun** [comment]
This is happening for me as well. Is this considered a bug that will be resolved?

_Environment:_
- Mac OS X 10.10.4
- Framer Studio 1.12.5
- Sketch 3.3.2

**Comment by lashan** [comment]
I just wanted to confirm that I'm getting the same issue as well. Is there any work around for this issue?

Mac OS X 10.10.5 — Framer Studio v54 — Sketch 3.6

**Comment by nvh** [comment]
This should be fixed with the latest Sketch and Framer, please open a new issue if you encounter any more problems.
