### ISSUE TITLE
Upgrade Animation Options to take start, end, and stop properties

### ISSUE THREAD

**Issue by uxdiogenes** [koenbok/Framer#111]
I'm always wanting to animate an object hiding, and then remove it when the animation is complete, so it doesn't keep getting click events, etc. For example, lets say I create a layer with a hidden state:

```js
var imageLayer = new Layer({
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  opacity: 0
});
imageLayer.states.add({
  showing: {
    opacity: 1
  },
  hidden: {
    opacity: 0
  }
});
```

I want to animate to the hidden state and then after that animation is complete, `display: none;`, or `visibility: hidden;` it.  Normally, I would need to do something like this:

```js
imageLayer.on(Events.StateDidSwitch, function (from, to) {
   if (to === 'hidden') { imageLayer.visible = false; }
});
```
and probably also:
```js
imageLayer.on(Events.StateWillSwitch, function (from, to) {
   if (to === 'showing') { imageLayer.visible = true; }
});
```

This is code I have to write pretty much every time I hide something. Instead, why not  upgrade animation objects to take `start`, `end`, and `stop` callback functions to match up with the events, allowing stuff like:

```js
imageLayer.states.switch('hidden', {
   end: function () { imageLayer.visible = false; },
}, false);
```

I could see this being pretty useful wherever takes an animation options object (`animate()`, `states.animationOptions`, etc.)

**Comment by uxdiogenes** [comment]
@koenbok Please don't forget about this with all the fancy new additions :). I butt up against it every time I make a Framer prototype.

**Comment by koenbok** [comment]
What about I add a start, pause, end option to every animation where you can pass callbacks.

`myLayer.addState("hidden", {opacity:0, finished: ((layer) -> layer.visibility = 0)})`

**Comment by koenbok** [comment]
Or maybe I'll call it `onStart, onStop, onEnd` or `onAnimationStart, onAnimationStop, onAnimationEnd`.

**Comment by uxdiogenes** [comment]
Looks good to me!

**Comment by uxdiogenes** [comment]
Looks like this bug is preventing me from using the technique I mentioned while I wait for these animationOption upgrades: https://github.com/koenbok/Framer/issues/173

**Comment by uxdiogenes** [comment]
For any observers, here's a workaround for #173, so you can using the technique I wrote above to set visibility before/after animating, just add this coffee script as the first line: `return if to is from` in your `Events.StateDidSwitch` handler. So that would make my JS look like so:

```
var setVisibilityWhenAnimating = function (layer, showStateName, hideStateName) {
  if (!showStateName) {
    showStateName = 'showing';
  }

  if (!hideStateName) {
    hideStateName = 'hidden';
  }

  layer.on(Events.StateWillSwitch, function (from, to) {
    if (to === showStateName) {
      layer.visible = true;
    }
  });
  layer.on(Events.StateDidSwitch, function (from, to) {
    if (to === from) { return; }
    if (to === hideStateName) {
      layer.visible = false;
    }
  });
};
```

**Comment by uxdiogenes** [comment]
I discovered another, even better use case for adding `onAnimationEnd`, etc., and that is to perform an action before/after a specific instance of a state change or animation, as opposed to all of a certain type. 

Lets say in one case I want to take an action `foo()` after a specific state change to state `bar`. If I do the following:
```
layer.once Events.AnimationEnd, ->
    foo()

layer.states.switch `bar`
``` 
Then I can run into the issue where the animation of that same layer from elsewhere will trigger that callback first, at the wrong point in time.

**Comment by nvh** [comment]
This will be solved in the new Animation and states API proposed in #378. Any property that isn't animatable will be set when the animation ends so
```
layer.animate
   opacity: 0
   visible: true
```
Will first animate to opacity 0 and the make the layer invisible. For the reverse, you should do
```
layer.visible = true
layer.animate
   opacity: 1
```

> Then I can run into the issue where the animation of that same layer from elsewhere will trigger that callback first, at the wrong point in time.

For this you can use `layer.once Events.StateDidSwitch, ->`

I'm going to close this one now, but please feel free to keep commenting or open a new issue if you have any more suggestions

**Comment by vennsoh** [comment]
I tried this.
However it seems that CSS display property is still block.

```
layer.animate
   opacity: 0
   visible: false
```
