### ISSUE TITLE
Color transitions and color overlays on views.

### ISSUE THREAD

**Issue by miekd** [koenbok/Framer#12]
Example of color overlays: I'm working on a prototype in it's wireframe stage and want to pulsate which areas are clickable. Having it pulsate to a little nice color, without having to add any complexity — like views on top of it — would be nice.

**Comment by nvh** [comment]
This has been fixed in the [Colors update](http://blog.framerjs.com/posts/enhanced-color-control.html) and will the problem mentioned will be fixed with the new Hints
