### ISSUE TITLE
State changes do not affect background image

### ISSUE THREAD

**Issue by pauginer** [koenbok/Framer#145]
I have a layer with an initial image and one state where the image property is different. When I trigger the event change, the image seems not affected. I would expect the state change to also affect the background image. Other properties such as opacity seem to work in the same situation.

I created an example to illustrate the issue here: http://codepen.io/anon/pen/vELbga

**Comment by yetimade** [comment]
This would actually be a really solid feature. Having to make multiple layers for each interactive element's on/off state is a huge pain.
