### ISSUE TITLE
Using a number to define element ids doesn't work with CSS

### ISSUE THREAD

**Issue by simonv3** [koenbok/Framer#16]
I'm inserting Framer into some other web content, and the way that div ids are defined is problematic for detection within css. 

I've fixed this on my own copy of framer.js with just changing how the id is defined by adding "framer-" to the beginning. I've also added a function to define to get and set the id and the element id to the supplied value:

```
View.define("viewId", {
      get: function() {
        return this.id;
      },
      set: function(value) {
        this.id = value;
        this._element.id = value;
        return this._element.setAttribute("id", this.id);
      }
    });
```

I would add this to source and push it to my fork, but I am having some whitespace issues and just coffeescript in general, plus, I'm not sure what the effects of this down the line might be, thought I'd post it here before doing anything like that.

**Comment by nvh** [comment]
Aaaaand it's fixed.
