### ISSUE TITLE
Preload script

### ISSUE THREAD

**Issue by koenbok** [koenbok/Framer#162]

**Comment by uxdiogenes** [comment]
Yes, please! In the mean time even a little module I could import that accomplished this somehow would be great, maybe it could show all layers onscreen for a second or two before setting their properties back to where they started.

**Comment by eelco** [comment]
Hi @uxdiogenes, this is an old ticket, there’s a preloader now. See Framer.Extras.Preloader.enable() (will be enabled by default when sharing). I think you might be talking about a different feature though, I don’t understand the remark about setting the properties back? Can you explain more?
