### ISSUE TITLE
apple watch resolution is slightly off

### ISSUE THREAD

**Issue by petergng** [koenbok/Framer#174]
framer device viewer's apple watch resolution is wrong at 320 x 400 pixels when it should be either 272 x 340 & 312 x 390

https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/WatchHumanInterfaceGuidelines/Layout.html#//apple_ref/doc/uid/TP40014992-CH22-SW1

**Comment by jornvandijk** [comment]
I'll fix this.
