### ISSUE TITLE
Layer group with hidden layer group reporting the wrong x coordinate

### ISSUE THREAD

**Issue by aroscoe** [koenbok/Framer#180]
Using the updated Sketch to Framer importer (using the Sketch Beta). I have a layer group with two more layer groups inside. Each sub layer group has the same size circle inside of it and they are located in the same spot. When both layer groups are visible the x coordinate for the parent layer group is correct. When one of the sub layer groups is hidden the x coordinate is completely different.

**Comment by koenbok** [comment]
Hey Anthony, any chance you can share the Sketch file with support@framerjs.com?

**Comment by aroscoe** [comment]
Sent.

**Comment by benjaminnathan** [comment]
Investigating and documenting this issue here: https://github.com/bomberstudios/sketch-framer/issues/92
Thanks @aroscoe!
