### ISSUE TITLE
Translate event.x/event.y to Framer coordinates

### ISSUE THREAD

**Issue by prokilogrammer** [koenbok/Framer#184]
I am trying to draw a layer at the point where a user clicked/touched on the screen. But the x and y values from event object passed with the click handler are in the browser coordinate system. Is there a way to translate it to Framer coordinate system so that I can pass this value to x,y params in new Layer() call?

Edit: Of course, this isn't a problem when testing on a frameless browser on a phone because app size = browser size.

**Comment by Cryclops** [comment]
Additionally, this causes issues when trying to look at event.offsetX inside a device frame (e.g. `Framer.Device.deviceType = "iphone-5s-spacegray"` vs. on a physical phone. You'll need to write a helper function to convert between the two.

**Comment by nvh** [comment]
This should have been fixed with the latest [point conversion](https://github.com/koenbok/Framer/pull/388) updates. I'm closing this issue, but please feel free to open a new one or keep commenting if you have any questions
