### ISSUE TITLE
Utils.isTablet() returns "false" on iPad Air Gen1

### ISSUE THREAD

**Issue by marckrenn** [koenbok/Framer#187]
Tested only on iPad Air Gen1 with Frameless and Safari. Can someone double-check this bug with another iPad generation or even an Android tablet? Thanks.

**Comment by koenbok** [comment]
Hey we just fixed a bunch of bugs with this last week. Could you update to the latest version (File > Update Framer) and double check? If it persists, I'd love to see the output of:

`print navigator.userAgent`

**Comment by marckrenn** [comment]
FramerStudio should be up-to-date. I'm currently running 1.11.1

print.navigator.userAgent returns:

Mozilla/5.0 (iPad; CPU OS 8_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B410

**Comment by koenbok** [comment]
Yes, but the Framer.js library can be updated apart from Studio :-)

**Comment by marckrenn** [comment]
Oh, I see. Didn't know that, I'm sorry. I thought I was using the latest Framer.js as I've just created the project like 10 minutes ago...

Yes, it works now.

**Comment by koenbok** [comment]
Yeah we sometimes update the Framer.js lib between Studio updates. For bugs like this :-)

Good to hear it works!
