### ISSUE TITLE
Mirroring doesn't work

### ISSUE THREAD

**Issue by offirg** [koenbok/Framer#188]
There's not sign of Mirroring actually working:

Mirror -> 'Open in browser' doesn't do anything
Mirror -> 'Copy link' doesn't capture a link. Pasting afterwords doesn't paste anything.
127.0.0.1:8000 shows an empty projects list
Android Framer app does not recognize any project.

**Comment by nvh** [comment]
I'm going to close this, because of inactivity, but feel free to open a new issue if you encounter another problem.
