### ISSUE TITLE
Site WebKit detection does not recognize WebKit in tweetbot mobile iPhone

### ISSUE THREAD

**Issue by spllr** [koenbok/Framer#19]
Alert informs WebKit is required. 

## Steps to reproduce

Visit framerjs website via tweetbot on iPhone (iPhone 4, iOS 6)

### Expected result

Either have access to site or get iPhone specific warning.

### Actual result

Warning appears with generic WebKit required message.

![image](https://f.cloud.github.com/assets/131222/416447/d99a2042-ac4d-11e2-94ef-12898baa6633.jpg)

**Comment by nvh** [comment]
Look at that old alert! This must be fixed by now? Is it? Yes it is!
