### ISSUE TITLE
Can't set video property on VideoLayer using options object

### ISSUE THREAD

**Issue by mattsjohnston** [koenbok/Framer#197]
After updating to the latest release of Framer Studio, if you set the `video` property on the options object, Framer will through the following error:

```
Uncaught TypeError: Cannot set property 'src' of undefined
```

After some brief exploration, it looks like what is happening is that the `video` option is calling the [video setter](https://github.com/koenbok/Framer/blob/master/framer/VideoLayer.coffee#L24) before this.video has been defined.

In the meantime users can get around this error by setting videoLayer.video specifically after instantiating it rather than passing it in the options object.

**Comment by koenbok** [comment]
Thanks @mattsjohnston!
