### ISSUE TITLE
Firefox on Mac OSX

### ISSUE THREAD

**Issue by wesamly** [koenbok/Framer#2]
Hi,
The included example produces the following error on Firefox 17.0.1 / Mac OS X 10.8.2:
WebKitCSSMatrix is not defined

Only gets empty page with the pattern background.

good luck.

**Comment by nvh** [comment]
This has been a while ago, and [Firefox has decided to implement WebKitCSSMatrix](https://bugzilla.mozilla.org/show_bug.cgi?id=717722). It already works in the Devoper preview, and is expected to land in 48. I'm closing this issue for now, as we're not expected to put any work into Firefox support until this lands in their stable.
