### ISSUE TITLE
WebKit detection does not work for apps saved to the iPhone home screen

### ISSUE THREAD

**Issue by tkeller** [koenbok/Framer#20]
Downloaded Framer, ran it locally, pointed mobile Safari to it, runs great on mobile Safari.

The problem arises when I then tap the Share icon in mobile Safari and choose "Add to Home Screen". When I run the app from its new Home Screen icon, it throws the "only WebKit browsers are currently supported" error.

Dismissing the error, the app seems to work fine, but the error is pretty annoying to have on every page load.

I always try to run prototypes from a Home Screen icon to eliminate the mobile Safari browser chrome, which is otherwise in the way.

![photo 715](https://f.cloud.github.com/assets/44362/500349/2a7cc4ae-bc72-11e2-9d9b-5db0b6b110db.png)

**Comment by nvh** [comment]
Fixed, see #19
