### ISSUE TITLE
Typos in docs

### ISSUE THREAD

**Issue by jake** [koenbok/Framer#206]
Didn't see the code for the docs anywhere, but spotted this typo when pasting the example into Framer Studio.

```
# Create a new ScrollComponent
scroll = new ScrollComponent({width:100, height:100)}
```

the `}` and `)` are transposed.

Additionally, in the "Learn to Import" section, the following code doesn't actually run when pasted into Framer Studio, because "import" is a reserved word.

```
# This imports all the layers of "design" into import
import = Framer.Importer.load "imported/design"

# Set the opacity of layerA 
import.layerA.opacity = 0.5
```

**Comment by benjaminnathan** [comment]
Thanks for the heads-up Jake. Will fix this right now.

**Comment by jake** [comment]
ah, I see... site is at motif/FramerSite? in which case, this is the wrong end... different typo now, hah :)

https://github.com/motif/FramerSite/commit/4751232c2aa0b5b5a5a61ac4d9c75d3c8ae1e227

**Comment by benjaminnathan** [comment]
Haha snap. Well spotted. Got it now. 😊
