### ISSUE TITLE
borderRadius is not working

### ISSUE THREAD

**Issue by swillis** [koenbok/Framer#207]
Try as I might, I cannot get the borderRadius property working. If I download any of the examples from from the framer site then they work fine, but if I reproduce them in the framer/project directory then I cannot set the borderRadius.

Am I missing something?

**Comment by marckrenn** [comment]
borderRadius works fine for me.

Maybe try to "File -> Update Framer" as your framer file could be old and/or buggy.

Also if you can share the said project with us so we can take a look at it.

**Comment by Clarko** [comment]
Another common gotcha is forgetting to set force2D:true on sublayers when you're setting the borderRadius of a superlayer.

e.g. If you remove line 5 of the following project, borderRadius breaks.

http://share.framerjs.com/omy6xbteemav/

**Comment by joshuarule** [comment]
"Update Framer" worked for me when framer didn't recognize `scroll = new ScrollComponent`

**Comment by nvh** [comment]
I'm going to close this due to inactivity. Please feel free to open a new issue or keep commenting if you want to follow up on this.
