### ISSUE TITLE
mouseWheelEnabled Doesn't Trigger Scroll Events

### ISSUE THREAD

**Issue by nlevin** [koenbok/Framer#209]
For scroll events, mouseWheelEnabled = true doesn't properly listen to Events.Move.

So for example:

```
scrollExample.mouseWheelEnabled = true

scrollExample.on Events.Move, ->
   # this will be triggered onDrag, but not when you scroll with your mouse 
   Thing.opacity = Utils.modulate(scrollExample.scrollY, [0, 100], [0, 1], true)
```

**Comment by rorysmyth** [comment]
this won't work
scrollRegion.propagateEvents = false

but this will
scrollRegion.on Events.Scroll, (e) ->
	e.stopPropagation()

**Comment by nvh** [comment]
@rorysmyth is right that `Events.Move` is triggered by draggable, so only on drag, and `Events.Scroll` is the event that is used for detecting scrolling in a `ScrollComponent`.

I agree that this is confusing and created #396 to discuss a fix. Please feel free to continue the discussion there.
