### ISSUE TITLE
Cmd+Click Links in Chrome Breaks Framer "Share" links

### ISSUE THREAD

**Issue by nlevin** [koenbok/Framer#210]
Try cmd+clicking the prototype in this tweet to open it in a new tab:
https://twitter.com/nlevin/status/593797784328904704

Notice it doesn't work, unless you refresh.

Same thing with the list of examples at the bottom of the post here:
http://blog.framerjs.com/posts/dragging-scrolling-paging.html

Only seems to happen in Chrome.

**Comment by nvh** [comment]
This was a while ago, and I can't reproduce it. Please feel free to open a new issue or keep commenting if you want to follow up on this.
