### ISSUE TITLE
Recording prototype interactions

### ISSUE THREAD

**Issue by nlevin** [koenbok/Framer#211]
Would be nice to be able to record a session from studio, with or without the device frame. This is useful for sharing on facebook / twitter / or internally at companies to give people a quick idea of what's in the prototype without having to play with all of it.

The workflow most people probably do today with Quicktime or other screen recorders isn't too bad, but a lot of people might not know about it.

Bonus: export to gif ;-)

**Comment by mrrocks** [comment]
:+1:

**Comment by cemre** [comment]
+1

**Comment by pxsmith** [comment]
:+1:

**Comment by theposch** [comment]
+1

**Comment by nvh** [comment]
While this is a good idea, and we're definitely considering this, it is technically a feature request for the Mac App app and not Framer Library. I'm going to close this for now, but please feel free commenting or responding to this.
