### ISSUE TITLE
layer.screenFrame is incorrect when called on a ScrollComponent sublayer

### ISSUE THREAD

**Issue by Clarko** [koenbok/Framer#214]
The numbers are correct when the scroll position is 0, but then they quickly become incorrect as you scroll.

It looks like it’s calculating its screenFrame correctly, and then adding the ScrollComponent's scroll position to it. So if you scroll 500px down, the screenFrame.y values of sublayers will be 500px lower than they ought to be.

Test case at http://share.framerjs.com/lnsvexc2xsk8/

**Comment by koenbok** [comment]
Good one!

**Comment by mrrocks** [comment]
I beliebe this has been fixed in the last update :)

**Comment by Clarko** [comment]
Indeed!

http://share.framerjs.com/r5q5kv6dx0vk/
