### ISSUE TITLE
[Proposal] Support for 120Hz+ monitors

### ISSUE THREAD

**Issue by jchavarri** [koenbok/Framer#217]
I've recently started using FramerJS to prototype gestural interaction applications with large screens (I promise to post a video on FB once there is something ready to show). So far I'm loving it, but I found it weird that in TVs or monitors with a high refresh rate (120Hz or more) all the animations get way slower. Around 2x slower. 
It could be related to this: http://lists.w3.org/Archives/Public/public-web-perf/2013Aug/0057.html

My question: would it be possible to add a global property to a Framer object (maybe a speed property to the Animation class?) so that the developer can instantly adapt animations to these type of devices?

**Comment by koenbok** [comment]
Hey, interesting. You can try and set the Framer loop to half or twice the speed:

https://github.com/koenbok/Framer/blob/master/framer/AnimationLoop.coffee#L26

`Framer.Loop.delta = 1/60/2`
`Framer.Loop.delta = 1/60*2`

**Comment by koenbok** [comment]
Let me know how that goes! I'm curious :-)

**Comment by jchavarri** [comment]
That's exactly what I was looking for, thanks for the quick answer!

Today I was making more tests with different resolutions (4K, FullHD), and cables (HDMI and DVI) but it seemed to work just fine -i.e. without any delta modifications-. It's very strange, as I'm 100% sure that all the animations were delayed the day before, even when loading regular sites that use requestAnimationFrame().

In any case, the graphic performance (even on 4K) is outstanding, Framer just keeps the pace at 60fps at very high screen resolutions! My next goal is to check how it behaves with multiple image loading + HD videos.

I'll make sure to send you a proper update with the results :)
