### ISSUE TITLE
Support for folder name in module

### ISSUE THREAD

**Issue by angelathewebdev** [koenbok/Framer#225]
I'm trying to add a folder to the module
```
keyboard = require "components/keyboardModule"
```

And I get the following error output
```
Error: Module components/keyboardModule can't be found
```

I also tried using `.coffee` extension, but no luck there either.

**Comment by nvh** [comment]
Although this is more of an issue about the Mac app, there's a fix for this in the works. Expect it in a beta soon!

Closing this issue for now, please feel free to comment or open a new issue if you have anything to add.
