### ISSUE TITLE
Consider clobbering `_textSizeNode.style` in `Utils.textSize`

### ISSUE THREAD

**Issue by peteschaffner** [koenbok/Framer#227]
Currently, the style object of the cached text node is [being extended](https://github.com/koenbok/Framer/blob/master/framer/Utils.coffee#L763), but I wonder if it would be better to replace the node's style object on every invocation. Was there a reason for extending?

I just wrote a [Label module](https://github.com/peteschaffner/framer-label) and [this bit me](https://github.com/peteschaffner/framer-label/blob/master/index.coffee#L27) as `_textSizeNode` was retaining the `width` property, which gave me identically sized `Label`s after creating a "constrained" instance.

**Comment by koenbok** [comment]
Good point.

Fixed in https://github.com/koenbok/Framer/commit/7c13491e091b3178824f69fdcbad10522f5e59a3

**Comment by peteschaffner** [comment]
:+1: Thanks, Koen!
