### ISSUE TITLE
Not able to build the library

### ISSUE THREAD

**Issue by chinchang** [koenbok/Framer#229]
Node: 0.12.5
Command run: `make build`

Error: 
```
/Framer/node_modules/.bin/gulp" build:release
[01:32:44] Requiring external module coffee-script/register
module.js:338
    throw err;
    ^
Error: Cannot find module 'source-map'
```

**Comment by koenbok** [comment]
Really odd. Maybe remove your node_modules folder and try again?

Make sure you have npm => 2.0 installed.

**Comment by nvh** [comment]
This is over a year old, so closing. Please feel free to open a new issues if the problem persists.
