### ISSUE TITLE
Making a layer visible=false after TouchStart cancels TouchEnd

### ISSUE THREAD

**Issue by autonia** [koenbok/Framer#231]
Oof, just learned this one the hard way...

I would not expect Touch events to be affected by visibility.
Was attempting to implement a simple up/down state for a button.

**Comment by jordandobson** [comment]
Maybe try opacity instead. :)

Visibility indeed removes the ability for events to succeed.

**Comment by autonia** [comment]
Yeah, I did end up using opacity. Seems like you're using "visible" as a stand-in or overlap with "enabled" here.

**Comment by nvh** [comment]
The thing is that you usually don't want to interact with invisible layers (and usually you do want your interactions to happen on the underlying layers). This is default web-behaviour as well, so I don't think we will change this in the future. Closing, Please feel free to continue the discussion op open another issue.
