### ISSUE TITLE
snapToPage() gets cancelled by PageComponent

### ISSUE THREAD

**Issue by SableRaf** [koenbok/Framer#233]
It is confusing tom many people that snapToPage() won't work from within a PageComponent:

https://www.facebook.com/groups/framerjs/permalink/691088261018248/
https://www.facebook.com/groups/framerjs/permalink/687287008065040/
https://www.facebook.com/groups/framerjs/permalink/684221775038230/
https://www.facebook.com/groups/framerjs/permalink/674981579295583/
https://www.facebook.com/groups/framerjs/permalink/711011342359273/

I read Koen saying that he was working on this back in June (https://www.facebook.com/groups/framerjs/permalink/687287008065040/?comment_id=696222527171488&offset=0&total_comments=11&comment_tracking=%7B%22tn%22%3A%22R0%22%7D) but since I couldn't find a commit, I'm posting this issue for the sake of bug tracking. I hope that's ok :)

**Comment by jonastreub** [comment]
This should be fixed with the latest build https://github.com/koenbok/Framer/commit/effb39956b448a7197904ef4f86da8b2c8feca17
