### ISSUE TITLE
Text Suggestion dropdown gets stuck on screen

### ISSUE THREAD

**Issue by edchao** [koenbok/Framer#234]
<img width="215" alt="screenshot 2015-07-21 14 12 15" src="https://cloud.githubusercontent.com/assets/82231/8812719/aacd9e0c-2fb2-11e5-818f-c0e3eea74356.png">

Occasionally text suggestion will not be dismissible.  It just gets stuck on the screen.  Refreshing causes framer studio to render a white screen.
Framer Version 1.12.5 (1358)

**Comment by nvh** [comment]
I'm going to close this due to inactivity, please feel free to open a new issue if you want to follow up on this.
