### ISSUE TITLE
Screen.width effected by Device.contentScale

### ISSUE THREAD

**Issue by Superpencil** [koenbok/Framer#240]
Input
```coffeescript
reSize = ->
	print Screen.width
	Framer.Device.contentScale = (Math.ceil Screen.width / 240) / 10
window.onresize = () ->
  reSize()
reSize()
```

Output
```bash
» 1807.5
» 907.5
» 1820
» 911.25
» 1825
» 913.75
» 1830
» 916.25
```

**Comment by jchavarri** [comment]
I think this is the expected behavior. 

`contentScale` can go from 0.5 to 1. If it's 0.5, then the screen width and height will double, and you'll get 4x the number of pixels to work with (retina).

What are you trying to achieve? I'm curious :)

**Comment by Superpencil** [comment]
OK! I was trying to get my animation to scale to whatever device width it was put on ^^
