### ISSUE TITLE
Origin not used in width/height/x/y

### ISSUE THREAD

**Issue by philworthy** [koenbok/Framer#246]
Firstly, great work! Framer is amazing!
Now I'm not sure if this is an issue, so please just ignore if it's intentional, but I've noticed that setting width and height (or reading x/y) of a layer doesn't seem to respect the origin point in the same way that setting its scale does (it seems to use the top left).
Is this intentional?
(apologies if this is the wrong forum for such a question)

**Comment by IanBellomy** [comment]
This is not the answer you're looking for but...

Framer uses div elements to display the visuals of Layers. The width and height of the layer map directly to the width and height properties of the element, which is always calculated from the top left. In contrast, Framer uses the element's transform property for scale and rotation (and 3D transformations). The good news is that the origin for these changes is adjustable! The value resides in the div's [transform-origin CSS property ](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin). If you need, you can access this in framer like so:

layer.style.transformOrigin = "0% 0%"  # This sets the origin to the top left so to match the width and height origin.

**Comment by nvh** [comment]
As @IanBellomy said, this is expected behaviour. Please feel free to open another issues if you find any more bugs and ask questions our [facebook group](https://www.facebook.com/groups/framerjs/)  for a quicker response time.
