### ISSUE TITLE
Border radius + scale

### ISSUE THREAD

**Issue by florianpnn** [koenbok/Framer#247]
When I create a layer with a border-radius of 50% and scale it, the circle I get isn't sharp.
I try with setting it up with an integer and I get the same result.

You can find an example here : https://dl.dropboxusercontent.com/u/4822469/Framer/borderRadius-pixels.framer.zip

**Comment by koenbok** [comment]
That is normal. The scale takes the pixels it has, and scales them on the GPU (blazing fast). If you want to keep your corners crisp you can do two things:

- Animate the width and height (on the CPU, slow).
- Render the layer at twice the size initially, make the initial scale 50%.

**Comment by florianpnn** [comment]
Make sense now that you explain it.
I'll go for the first solution while animating the position as well to make sure it reproduces the scale.

Thanks for the quick answer!
