### ISSUE TITLE
Git repo appears to be in a bad state

### ISSUE THREAD

**Issue by WestonThayer** [koenbok/Framer#249]
Git takes issue with [this empty file](https://github.com/koenbok/Framer/blob/master/test/studio/PageComponentLockHorizontalDirectionExceptTopRow.framer/Icon%0D). Git thinks that a delete is always staged for that file, and it causes issues with cloning the repo. I assume it's OK to delete?

**Comment by edwinvanrijkom** [comment]
Thanks for the heads-up. Tried to reproduce some of the trouble that you are mentioning, but I didn't run into any problems. I've removed the empty file, regardless - for it doesn't make much sense to have it around either way :-)

**Comment by WestonThayer** [comment]
I can only reproduce it on Windows (luckily had a Mac handy that I could try it out on). Seems fixed now, my working set is clean. Oddly, GitHub for Desktop can open the repo just fine on OSX, but not on Windows, even with the fix.
