### ISSUE TITLE
Utils.delay doesn't allow passing parameters, unlike _.delay

### ISSUE THREAD

**Issue by frischmilch** [koenbok/Framer#251]
Maybe Utils.delay should allow sending arguments into the function.

[_.delay](http://underscorejs.org/#delay)

This was confusing to solve with closures in a for loop. facebook group [provided some alternate solutions](https://www.facebook.com/groups/framerjs/permalink/752692391524501/?comment_id=752934004833673&offset=0&total_comments=13&comment_tracking=%7B%22tn%22%3A%22R%22%7D), but it required some more changes to the code. 

[Example Code/Solution](http://share.framerjs.com/m1r0cgl50ge6/)

**Comment by joshpuckett** [comment]
I'm a bit confused, but in the example you posted, this works (passing a param to Utils.delay).

	allCards.forEach (card, i) ->
		timedifference = .5*i
		Utils.delay timedifference, ->
			print "changing card", card.name
			card.backgroundColor = Utils.randomColor()

**Comment by nvh** [comment]
I know this reply is a bit late, but this is a general scoping issue, that can be solved by: 
```
for card,i in allCards
	timedifference = .2*(i+1)
	do (card) ->
		Utils.delay timedifference, ->
			card.backgroundColor = Utils.randomColor()
```
or
```
button.on Events.Click, ->
	for card,i in allCards
		timedifference = .2*(i+1)
		changeCard(card,timedifference)
		
changeCard = (card, timedifference) ->
	Utils.delay timedifference, ->
		card.backgroundColor = Utils.randomColor()
```

I don't think we want to add more complexity to `Utils.delay` to solve this, so closing this issue. 

Please feel free to open a new issue or keep commenting if you want to follow up on this.
