### ISSUE TITLE
The Framer.zip is not found.

### ISSUE THREAD

**Issue by steveleec** [koenbok/Framer#253]
I am following the Get Started and after clicked on http://framerjs.com/static/downloads/Framer.zip,
I got "Sorry, this page could not be found". Is that something you'll be fixing or there is no more support for Framer.js outside F. Studio?
Thanks!

**Comment by vennsoh** [comment]
Try http://builds.framerjs.com for the latest Framer.js

Framer generator is outdated and still awaiting a new upload.

**Comment by nvh** [comment]
The link should be working again, and the latest builds are indeed on http://builds.framerjs.com
