### ISSUE TITLE
Framer Generator

### ISSUE THREAD

**Issue by filipeperdigaosousa** [koenbok/Framer#254]
Hi
Currently I am trying to use Framer.js on my windows machine but I am having some troubles.

I followed this tutorial 
http://www.prototypingwithframer.com/framer-on-windows-with-atom/
and there is one thing that I dont undertood.

How can I import projects from Photoshop or Sketch without Framer Studio? I saw that you have a section in your github readme file that say we need to use Framer Generator, but where can I found it?
Does it work with windows?

I understood that we can use Framer.Importer to import content, but I need a previous step that transforms Photoshor or Sketch project into a correct folder and file structure able to be loaded by Importer?

**Comment by vennsoh** [comment]
On this page, https://github.com/koenbok/Framer > Get Started section, you have your link to Download the Framer.js + Framer Generator bundle. http://framerjs.com/assets/static/downloads/Framer.zip 

Framer.js is outdated and so it Framer Generator.
For the latest Framer.js build, builds.framerjs.com

Framer Generator is yet to be updated.
@koenbok will you be able to address this?

**Comment by koenbok** [comment]
Yes, likely next week.
