### ISSUE TITLE
Framer + Generator download in README downloads an older version of Framer

### ISSUE THREAD

**Issue by rkho** [koenbok/Framer#256]
I found that the link on Line 12 of README.md links to the download of an older version of Framer.js, which does not include the `DeviceComponent` class and added to some confusion on my end when I tried to use it to set a device type for my project.

The workaround I found was to clone the entire open source repo down to my machine and run `gulp build:release` to grab the latest version of the library for my uses.

It'd be great if we could compress this into an updated zip file for users to install.

**Comment by imp17** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

cbox101@naver.com 님께 보내신 메일 <[Framer] Framer + Generator download in README downloads an older version of Framer (#256)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by vennsoh** [comment]
try builds.framerjs.com

**Comment by rkho** [comment]
Awesome, thanks for pointing me there.
