### ISSUE TITLE
Missing images at //resources.framerjs.com?

### ISSUE THREAD

**Issue by ursooperduper** [koenbok/Framer#258]
When I export a Framer prototype to my site or share it via Framer Studio, I'm seeing 403 errors when requesting a background image:

```
http://resources.framerjs.com/static/DeviceResources/iPhone-5s-silver-hand.png Failed to load resource: the server responded with a status of 403 (Forbidden)
```

**Comment by ursooperduper** [comment]
Found the problem, I had camel-cased asset names. :\

**Comment by jornvandijk** [comment]
No problem, thanks for reporting anyway!
