### ISSUE TITLE
No device configuration for 1440px (@4x/xxxhdpi) Android devices

### ISSUE THREAD

**Issue by mcilvena** [koenbok/Framer#287]
It would be really handy if we could get devices configurations added for 1 or more 1440px Android devices.

Facebook have released device images for Galaxy Note 5 and Nexus 6P (https://facebook.github.io/design/devices). These could possibly be used for the device images.

**Comment by mcilvena** [comment]
I'd be more than happy to submit a pull request for these changes.

**Comment by jornvandijk** [comment]
There is a massive device + hand update coming up.
