### ISSUE TITLE
event.offsetY is reporting unexpected values

### ISSUE THREAD

**Issue by noAlvaro** [koenbok/Framer#295]
Hi,

I am listening for events in an 140x140 layer, but the `event` param inside the listener handler reports an `offsetY` property that simply resets after pixel 79 (i.e.: 1, 2, 3 ... 78, 79, 0, 1, 2 ... etc).

I'm really puzzled with this and already checked everywhere in the code to see if something could be impacting this property, but I'm pretty much sure that there's nothing at all. Scope is correct, and even the `event.offsetX` is working as expected (from 0 to 140).

I'm posting just for the chance that there's anything yet to be reviewed on this.

Thanks!

**Comment by nvh** [comment]
This has probably recently been fixed by the new point conversion API, so I'm closing this. Please feel free to open a new issue or comment here if you want to follow up on this.
