### ISSUE TITLE
Anchoring API

### ISSUE THREAD

**Issue by euforic** [koenbok/Framer#3]
Would it be posible to add `top, bottom, left, right` params for element to allow for easier fluid layouts. Similar to how Appcelerator's Titanium does it?

example:
```js
var view = Titanium.UI.createView({
   borderRadius:10,
   top: 10,
   left: 10,
   bottom: 10,
   right: 10,
   backgroundColor:'red'
});
window.add(view);
```

**Comment by jordandobson** [comment]
This sounds a lot like constraints in auto layout... or absolute positioning using top, left, bottom, right to it's parent. 

I for one would love this.
