### ISSUE TITLE
Super layer overflow property unexpectedly resets to 'hidden'

### ISSUE THREAD

**Issue by noAlvaro** [koenbok/Framer#300]
Hello again,

I'm trying to animate a `subLayer` outside the constraints of the parent `superLayer`, so I needed to change `superLayer`'s CSS `overflow` property to `visible`.

The thing is that the framework seems to kick the property back again to `hidden`, eventually.

I tried to work around this by setting the `overflow` property to `visible` every time and _just before_ the `animate` method call, but it doesn't help _every time_. Eventually it stills get `superLayer`'s `overflow` to `hidden` again.

Tried to set the property on `subLayer` and `superLayer`'s `AnimationStart` and `AnimationDidStart` events with just the same results. Won't do. About a third of the times `overflow` automatically goes to `hidden`. :(

Posting again in hope there's something to improve on that.

Thanks!

**Comment by jordandobson** [comment]
You want to use the clip property instead of CSS style.

MyLayer.clip = false

**Comment by jornvandijk** [comment]
Hey Alvaro, can you post questions in the group instead of as a ticket here? It is where we all hang anyway to sort stuff out :-) fb.com/groups/framerjs

**Comment by noAlvaro** [comment]
Thanks @jordandobson.
