### ISSUE TITLE
Dragging onto layer will still emit a Click event

### ISSUE THREAD

**Issue by noAlvaro** [koenbok/Framer#306]
layer = new Layer
    layer.on Events.Click, -> print 'issue'

... then drag from outside the layer, onto the layer: `issue` appears in the console.

I presume that a standard `Click` event should work only when the touch _starts_ and _ends_ over the same layer. Is this a bug or there's a better approach to restrict the `Click` events?

**Comment by nvh** [comment]
`Events.Click` is just indeed a shorthand for "mouseup" on desktop and "touchend" on touch devices. If you want to have the native "click" event, you can use:
```
layer = new Layer
layer.on "click", -> print 'issue'
```
I agree that this is counterintuitive, but there's probably a good reason for this. @koenbok can you elaborate?
