### ISSUE TITLE
Events.StateDidSwitch emits together with Events.StateWillSwitch

### ISSUE THREAD

**Issue by thijsm** [koenbok/Framer#307]
```
layer = new Layer
layer.center()

layer.states.add
	one:
		scale: 2
	two:
		rotation: 45

layer.on Events.Click, ->
	this.states.next()

layer.on Events.StateWillSwitch, ->
	print "Switching from state: ‘#{this.states.current}’"

layer.on Events.StateDidSwitch, ->
	print "… to state: ‘#{this.states.current}’"
```
…will output, when tapping three times:

![screen shot 2016-02-05 at 14 32 19](https://cloud.githubusercontent.com/assets/28934/12847695/54d1bac4-cc15-11e5-9200-3aef0ea6f359.png)

Works correctly on the first tap, but on the second and consecutive taps `StateDidSwitch` is called **together** with `StateWillSwitch`, and then again after 1 second, when the state *actually* finished switching.

**Comment by uxdiogenes** [comment]
This looks related to the sadly unloved issue here: https://github.com/koenbok/Framer/issues/173

**Comment by thijsm** [comment]
Is fixed!

In this commit:
https://github.com/koenbok/Framer/commit/a85d1df5811c949865672f020457222cac3eeff8
