### ISSUE TITLE
Request: window size query

### ISSUE THREAD

**Issue by tylerhowarth** [koenbok/Framer#31]
I couldn't find a way to request the browser height or width in Framer.  I wanted to do this so that I could run my Framer prototypes on both 3.5" and 4" screens.

My workaround was to include jquery in to my index.html and request using .height()

```js
viewportY = $(window).height();
```

I am using this to make a sticky footer work like this

```js
PSD.footer.y = viewportY - PSD.footer.height;
```

**Comment by nvh** [comment]
`Screen.size` to the rescue!
