### ISSUE TITLE
The framer.js is not the newest framer.js

### ISSUE THREAD

**Issue by wangpengchenggreen** [koenbok/Framer#313]
The framer.js of Framer.zip can not compile "borderRadius".

**Comment by vennsoh** [comment]
You might want to go to http://builds.framerjs.com/ for the latest framer.js

**Comment by wangpengchenggreen** [comment]
@vennsoh  Thanks!

**Comment by nvh** [comment]
If you're using the Mac App, you can also use 'Update Framer Library' from the file menu to update to the latest build
