### ISSUE TITLE
Scroll events are missing

### ISSUE THREAD

**Issue by maceuph** [koenbok/Framer#323]
The ScrollComponent only has onScroll defined. The documentation for Scroll Events mentions onScroll[Start | End] and onScrollAnimationDid[Start | End] event helpers. It looks like the definitions for the shortcuts are missing from Layer.coffee. 

scroll = ScrollComponent.wrap (layerA)
scroll.onScrollStart (event) ->
	print "Start"
	
scroll.onScrollEnd (event) ->
	print "End"

As a workaround, Events.ScrollEnd and friends still work

**Comment by nvh** [comment]
This seems to be fixed in the latest Framer Library. If you have more to add here please feel free to create a new issue.
