### ISSUE TITLE
BackgroundLayer not showing up

### ISSUE THREAD

**Issue by chinchang** [koenbok/Framer#331]
**Issue**: In the latest version (http://builds.framerjs.com/c264dd8/framer.js) of framer.js, `backgroundLayer` is not showing up.

**Reason**: Since a previous commit (7cbcd022), root elements have `background-color` of white set on them. And backgroundLayer are set to `z-index` of -1 which brings it under its parent's background.

Test case: http://codepen.io/chinchang/pen/oxGjjY?editors=0010

**Comment by quietshu** [comment]
Same issue here, `BackgroundLayer` is not working. I can only use `Framer.DefaultContext.backgroundColor = 'red'` to overwrite and set the background color.

**Comment by jordandobson** [comment]
This is changing… I believe you want to use Screen.backgroundColor now.

On Mon, Apr 11, 2016 at 11:59 AM, Shu Ding <notifications@github.com> wrote:

> Same issue here, BackgroundLayer is not working. I can only use Framer.DefaultContext.backgroundColor
> = 'red' to overwrite and set the background color.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/koenbok/Framer/issues/331#issuecomment-208499618>
>



-- 
Jordan Dobson • Designer / Developer • 425-444-8014 • JordanDobson.com

**Comment by koenbok** [comment]
Hmm works fine for me here in latest. But we are indeed moving away from this, because with 3d perspective the layers can "cut" each other, giving weird visual results.

**Comment by chinchang** [comment]
So you mean, `BackgroundLayer` is deprecated now and we use `Screen.backgroundColor` instead?

**Comment by nvh** [comment]
Yes `BackgroundLayer` is be deprecated in the near future, and `Screen.backgroundColor` is the desired way to this now.

I've just added a deprecation warning to BackgroundLayer: https://github.com/koenbok/Framer/commit/ca228809989d7c9ef98300a219ded0578a06ba28
