### ISSUE TITLE
Vertical PageComponent snaps to next page on click

### ISSUE THREAD

**Issue by Clarko** [koenbok/Framer#335]
PageComponents erroneously respond to clicks pages are added at "bottom"

It doesn't seem to matter how you have scrollVertical or scrollHorizontal configured, just that the pages are "bottom" instead of "right"

Weird thing: if you click multiple times in a row, only the first page seems to react. But if you wait a sec, subsequent pages will also go to next page on click.

http://share.framerjs.com/ztuq9qcawk7f/

**Comment by mrrocks** [comment]
This has just been fixed!

**Comment by nvh** [comment]
This indeed is fixed and works with the current version of framer: http://share.framerjs.com/96zgith2d8z8/
