### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by Sivilll** [koenbok/Framer#350]
Is there a way to get this for windows?  Or is it mac only?

**Comment by koenbok** [comment]
It's mac only for now :-)

**Comment by Sivilll** [comment]
Ok, that should be clarified on the website, to avoid confusion.

**Comment by kumarharsh** [comment]
It's not written anywhere on the website that this is Mac only. I've downloaded it TWICE(!!) just to unzip and see mac files :disappointed:
