### ISSUE TITLE
Dynamic ScrollComponent and updateContent

### ISSUE THREAD

**Issue by martincohen** [koenbok/Framer#356]
It seems that there's a bug in ScrollComponent. It doesn't scroll to the end. See the example here, you can clearly see it in a lot of examples online. Like this one:

http://share.framerjs.com/wrb1qm3ckl1k/

I got the same problem, updateContent() doesn't work at all. Any tips?

**Comment by nvh** [comment]
This has since been fixed, please verify that it works with an updated version of framer: http://share.framerjs.com/rn2653htzgd4/

If it doesn't feel free to open another issue
