### ISSUE TITLE
layer.ancestors not working

### ISSUE THREAD

**Issue by benstronaut** [koenbok/Framer#360]
Have a feeling this is a bug. When I use layer.ancestors on anything that has parents I get this in the console which looks like the logic to determine the parents, not an answer to who the ancestors are. 

 `<Function (context) { var currentLayer, parents; if (context == null) { context = false; } parents = []; currentLayer = this; if (context === false) { while (currentLayer.parent) { parents.push(currentLayer.parent); currentLayer = currentLayer.parent; } } else { while (currentLayer._parentOrContext()) { parents.push(currentLayer._parentOrContext()); currentLayer = currentLayer._parentOrContext(); } } return parents; }>`

**Comment by graemechapman** [comment]
I'm getting this too. As a workaround I have created my own function to produce the correct response - 
```
getAncestors = (currentLayer) ->
	parents = []
	while (currentLayer.parent)
		parents.push(currentLayer.parent)
		currentLayer = currentLayer.parent
	return parents
```

**Comment by awt2542** [comment]
It's a method so use layer.ancestors() instead :) I don't think this is reflected in the docs

**Comment by graemechapman** [comment]
Indeed it is! It's a bit odd that this doesn't follow the same style as layer.descendants though :confused:

**Comment by nvh** [comment]
Interesting. You are correct that it isn't consistent, we will consider updating it. For now, I've added a change to the docs (that will go live soon).
