### ISSUE TITLE
Ignore html property in state changes

### ISSUE THREAD

**Issue by martenbjork** [koenbok/Framer#362]
Sometimes when moving between states the html property is changed when it resembles a color. Strings such as "blue" and "#fff" are converted to their rgb(r,g,b) counterparts.

I know @nvh [did some work](https://github.com/koenbok/Framer/commit/7bd6aa722a07b0d21a148e7fd4222a13d2dace34) to work around this, but I can still trigger the string conversion (in Framer Studio v63) by using the following code:

```
lay = new Layer
	html: "blue"

lay.states.add
	"stateA":
		scale: 1

Utils.delay .01, ->
	lay.states.next()
	
Utils.delay .02, ->
	lay.states.next()
```

Expected: Layer is always rendered with the text "blue"
Actual: The rgb value briefly shows up inbetween states

Maybe just ignore the html property altogether?

**Comment by martenbjork** [comment]
Also, if you set the initial html value to "1", the value will briefly be rendered as "10".

**Comment by nvh** [comment]
Thanks for reporting!

This has already been fixed in the [animation-refactor](https://github.com/koenbok/Framer/tree/feature/animation-refactor) branch, and thus will be solved when that is merged into master
