### ISSUE TITLE
Some CSS properties are animatable but not all?

### ISSUE THREAD

**Issue by vennsoh** [koenbok/Framer#365]
Hi, 

I am using the latest Framer build.

When I try to combine Framer.js with GSAP. I notice some weird behaviour.
Eg: I can control the Framer layer translation, rotation, scaling, opacity with GSAP but I can't do box-shadow, border...

So there are some CSS properties that can be animated but some can't.

Do you know why?

**Comment by nvh** [comment]
I don't know GSAP that well, so I don't know why, but it would help tremendously if you could provide a sample project showing what exactly doesn't work.

**Comment by jonastreub** [comment]
I think this is about not being able to animate css properties through the style property on layer. As we might switch our rendering in the future away from css we do not want to have too many dependencies with that format.

**Comment by vennsoh** [comment]
Thanks gang @nvh @jonastreub 

I can't quite remember exactly the problem as it was quite a while ago...
But if I remember correctly... when I was trying to animate the CSS box-shadow using GSAP. I can't do it. 

But I found out interestingly, you can use GSAP to animate the Framer shadowX, shadowY, shadowBlur properties.

My dumb assumption is that Framer is doing some kind of "scaffolding" that is covering the CSS native box-shadow properties hence GSAP can't detect that? 

But anyway, I have solved that. So it is all good.
