### ISSUE TITLE
Code Folding and line breaks.

### ISSUE THREAD

**Issue by IanBellomy** [koenbok/Framer#368]
Not sure if this is expected behavior.

When folding is initiated on an item, the folding doesn't include content separated by more than one line break. For example, when folding a class declaration, if the class has any methods that are separated by two line breaks, the methods are not folded in.

<img width="241" alt="screen shot 2016-06-09 at 11 03 47 pm" src="https://cloud.githubusercontent.com/assets/17239616/15953245/ba5f8414-2e96-11e6-9aa2-7964d102aa49.png">

This only happens when initiating folding from the top level line. If you initiate folding on the empty line, things fold as expected.

**Comment by edwinvanrijkom** [comment]
Good catch! I'll add this to the internal backlog.

**Comment by IanBellomy** [comment]
(Looks like its fixed in v65.)

**Comment by edwinvanrijkom** [comment]
Thanks for confirming, @IanBellomy .
