### ISSUE TITLE
Framer Generator isn't working in Sketch v39

### ISSUE THREAD

**Issue by vennsoh** [koenbok/Framer#382]
With the new update to Sketch v39, Framer Generator on http://builds.framerjs.com has stopped working. Framer Studio is still working fine.

**Comment by koenbok** [comment]
Could you try the beta at http://framerjs.com/beta

**Comment by vennsoh** [comment]
Yup beta is working. I have Framer Studio. It is working fine. But the open source Framer Generator isn't. We are coding in JS at this agency hence we are relying on the github Framer.js. Hence the workaround is to generate the assets in Framer Studio and then later on copy the files to our own bootstrapped Framer.js folder which isn't ideal. Any chance we can export Framer generator as a standalone tool? Thanks (:

**Comment by koenbok** [comment]
Ah, I see! Let me check if I can update generator quickly for you.

**Comment by vennsoh** [comment]
That will be most appreciated thanks @koenbok

**Comment by koenbok** [comment]
Unfortunately this is not a quickie. We hope to fix it next week.

**Comment by vennsoh** [comment]
Any status update on this? (: @koenbok @nvh

**Comment by nvh** [comment]
I've just updated [Framer Generator](https://builds.framerjs.com/latest/Framer.zip). To make this process more streamlined in the future, we've switched out the backend providing the updates. Therefore the Updating from Framer Generator won't work this time, but after redownloading it once, it will update itself in the future.

**Comment by vennsoh** [comment]
@nvh much appreciated! Awesome!
