### ISSUE TITLE
Expose Events class

### ISSUE THREAD

**Issue by bensleveritt** [koenbok/Framer#383]
I'm looking to create a class that extends EventEmitter, and I wondered, rather than reinstalling EE3, we could have an Events class exposed? I'm starting to get to the point in a prototype where the complexity is getting a little out of hand, and am moving all communication to an event bus.

It's not a big deal, but could be useful. Maybe exposed in the Utils class?

**Comment by IanBellomy** [comment]
````coffeescript
class CustomEventEmmiter extends Framer.EventEmitter
	constructor: ->		
		print "intercepting constructor"
		super()
		
	emit: (eventName)->
		print "intercepting emit " + eventName
		super(eventName)


cee = new CustomEventEmmiter
cee.on "test", ->
	print "ok!"

cee.emit "test"
````
?

**Comment by bensleveritt** [comment]
That'll do just nicely. Many thanks!
