### ISSUE TITLE
use framer generator on windows

### ISSUE THREAD

**Issue by geor13** [koenbok/Framer#386]
Is there a way to use framer generator on windows ??? if not is there any other way i can import .psd files into framer.js???

Thanks for your time

**Comment by nvh** [comment]
While this is definitely would be interesting, it's not our focus currently.
If you export your files manually with photoshop, you can drop them in the "images" folder of your framer project and use them as images of a layer.

**Comment by geor13** [comment]
thank you for the reply and for your time...really appreciate it
