### ISSUE TITLE
Framer Generator produces an empty framer.js file

### ISSUE THREAD

**Issue by TommasoBertagnin** [koenbok/Framer#405]
I successfully created a project with the Framer Generator, however the framer.js file is empty, therefore causing an error when opening index.html
> Uncaught ReferenceError: Framer is not defined

My machine:
MacBook Pro (Retina, 15-inch, Mid 2015)
El Capitan 10.11.6

**Comment by wagerfield** [comment]
I am also experiencing this issue with Version 3.0.91 (110)

**Comment by koenbok** [comment]
I'll look into this.

**Comment by koenbok** [comment]
I just pushed a new version (with Figma support too!). Let me know if that fixed it:

**Comment by TommasoBertagnin** [comment]
Yes, it works wonderfully! Thank you
