### ISSUE TITLE
How To Contribute to Framer Generator

### ISSUE THREAD

**Issue by fx-lange** [koenbok/Framer#415]
Hi @koenbok,

we at IXDS started looking into the Framerjs workflow again and for some prototypes it already worked quite well. We have some ideas in mind to improve the workflow by working on the Sketch parser / Framer Generator - like being able to detect and parse Sketch Symbols. 

It seems that the Framer Generator is closed source. Is this on purpose? At least I couldn't find the source. If I remember correctly the Plugins/Generator for Framer 2 where just open javax files. 

I really like your approach to have a list like this https://github.com/koenbok/Framer/wiki/Contributing:-Wanted-Features but it is only for the JS library right? We would actually like to contribute to the generator. 

Any chance to contribute to / collaborate on this?

Best,
Felix

**Comment by koenbok** [comment]
We have been jumping back and forth between a native implementation in Sketch and a plugin. We just revamped our implementation again, but I think we're going to keep it closed for now. Main reason is that it just takes time to open stuff up and we have to be picky with resources. We might revamp at a later point.
