### ISSUE TITLE
Default sample does not work (animateToNext() is not a function)

### ISSUE THREAD

**Issue by yannlossouarn** [koenbok/Framer#424]
The default sample code and the Get Started page on GitHub do mention the following sequence, that does not comply with current release of Framer.js, and triggers a Script Error:
`	imageLayer.animateToNext()`

AFAIK it should be replaced by:
`	imageLayer.states.next()`

Best regards, thanks for your work!

**Comment by yannlossouarn** [comment]
Erratum:
`imageLayer.states.next()`
is deprecated. Prefer:
`imageLayer.stateCycle()`

**Comment by spaceghoul** [comment]
The animationOptions are also not being set according to the new API.  I opened #427 to address both issues with the basic demo.

**Comment by nvh** [comment]
This one is fixed by https://github.com/koenbok/Framer/pull/427. Thanks for reporting @yannlossouarn, and thanks for fixing @spaceghoul!
