### ISSUE TITLE
Request: autoAlpha

### ISSUE THREAD

**Issue by vennsoh** [koenbok/Framer#438]
Can I suggest Framer to implement something similar to GSAP like autoAlpha?

The idea is that when some elements animate, instead of using opacity:0 it will animate to opacity:0 and also set visibility = hidden.

I have seen too many prototypes that have opacity: 0 but the elements are still on the screen hence it interferes with the click events.

**Comment by vennsoh** [comment]
Figure the new API can solve this.

**Comment by jordandobson** [comment]
Sometimes you want the blocking... you can add visible:false to the state or animation and it will apply once the animation is done.

**Comment by vennsoh** [comment]
Thanks @jordandobson I have added a new API in Framer.js to do this for my projects.

**layer.autoAlpha**

0 will make opacity = 0 and layer.visible = false.
1 will do the reverse.
