### ISSUE TITLE
Request: Make "point" animatable

### ISSUE THREAD

**Issue by RayPS** [koenbok/Framer#448]
```
layerA = new Layer
	point: 100

layerA.animate
	point: 200
```

**Comment by nvh** [comment]
This has been in master since https://github.com/koenbok/Framer/commit/2ddfe04d45c4d6fe38fd1389410ea5af3218638b, which is available in the latest stable of Framer as of now.

**Comment by RayPS** [comment]
Didn't know that as well, is the "Update Framer Library" function does matter with my Framer Studio version? I am using v73 because i didn't renew my license.

**Comment by eelco** [comment]
Yep, should work on any version. If you find that anything breaks in Framer (the app), let us know.
