### ISSUE TITLE
Screen not present in general Framer.js library?

### ISSUE THREAD

**Issue by briannhinton** [koenbok/Framer#450]
I'm not sure if this is an actual issue or not. The console states that BackgroundLayer is deprecated, and to use Screen.backgroundColor = "yourColor". Screen isn't coloring the background. Is this feature not supported outside of Studio?

**Comment by eelco** [comment]
It’s there, but you will need to have a device set up, including its context. In Framer Studio this will be generated for you, but if you’re using just the library you can do

```
Framer.Device = new Framer.DeviceComponent();
Framer.Device.setupContext();
```

to get the default device. Setting `Screen.backgroundColor` will then work.

For a fullscreen device, pass the option `{deviceType: "fullscreen"}` to the DeviceComponent constructor.

**Comment by briannhinton** [comment]
Ahh thanks @eelco. That makes sense.
