### ISSUE TITLE
Should layer.states.next() be in documentation?

### ISSUE THREAD

**Issue by IanBellomy** [koenbok/Framer#473]
It's not, but I'm wondering if it should be... 

Was confused why a student who had obviously read the documentation was working with the state system yet couldn't figure out how to cycle through states...

**Comment by nvh** [comment]
We have replaced it with `layer.stateCycle()` as part of the new animation API, you can read all about that here: https://github.com/koenbok/Framer/wiki/Animation-Upgrade-Guide#cycling

**Comment by IanBellomy** [comment]
*facepalm* I thought I had looked at that, but I did not. Thanks for the link!
