### ISSUE TITLE
TextLayer explicitWidth set to true after updating text

### ISSUE THREAD

**Issue by nsimonson** [koenbok/Framer#482]
When setting a TextLayers text value, after initial construction, explicitWidth is getting set to true. This results in improperly constraining the layer size on subsequent text updates.

**To recreate**
``` coffeescript
textA = new TextLayer
	text: "Hello"
	
textA.text = "Hello there"
textA.text = "Hello there buddy"
```

You can work around this issue by setting explicitWidth to false after updating the text property.
``` coffeescript
textA.text = "Hello there"
textA.explicitWidth = false
```

**Comment by nvh** [comment]
Great catch! I just pushed a fix for this stupid mistake :)
