### ISSUE TITLE
Feature Request: Flow component - Switch Instant transition

### ISSUE THREAD

**Issue by agisilaos** [koenbok/Framer#496]
Playing around with Flow Component today I saw that a super important animation is missing, `showNext` or `ShowOverlayCenter` doesn't provide the desired animation which is shown below.

I would like to start working on that issue. Any tips on how and where should I check and get started?

![demo](https://cloud.githubusercontent.com/assets/10944108/25559011/4af58a5c-2d3b-11e7-811c-0f23edf4bd69.gif)

**Comment by marckrenn** [comment]
So, you're requesting instant transition between FlowComponent screens, right?

If so, I have some good news for you: It's already in. 
Just set the optional `animate: false`-option like this:

```coffeescript
screenA.onClick ->
	flow.showNext(screenB, animate: false)
```
It's also in the [docs](https://framer.com/docs/#flow.showNext) (second example).

**Comment by agisilaos** [comment]
Yes, exactly! Wow, I didn't notice that! Thanks for bringing this to my attention @marckrenn
