### ISSUE TITLE
Framer studio not showing images in Cloud

### ISSUE THREAD

**Issue by stephcl** [koenbok/Framer#507]
Whenever I copy/paste layers from Sketch into Design, I get images that I can manipulate, animate, etc. in Code. However, once I upload it to Cloud, none of those images are visible. Only elements that I made in Design are visible, even though I can see everything in preview.

**Comment by ath92** [comment]
I'm having the same issue.

**Comment by eelco** [comment]
This was fixed in Framer v91, please re-open if you still see this issue.
