### ISSUE TITLE
TextLayer Problems

### ISSUE THREAD

**Issue by steveruizok** [koenbok/Framer#509]
Several people have pointed out on Slack that TextLayers weren't rendering layer sizes correctly. I took a look and believe I found the problem at TextLayer.coffee, line 121, where `@_element` should be `@_elementHTML`. As it is, the text is being given to the Framer layer (`_element`) without creating a child node (`_elementHTML`), but the styling functions are still attempting to hit the child node. See the code in https://framer.cloud/WSAxo.

```coffeeScript
@define "text",
    get: -> @_elementHTML.textContent
        set: (value) ->
            @_elementHTML.textContent = value
            @emit("change:text", value)

**Comment by nvh** [comment]
I've pushed a fix for this, incorporating this fix into the Framer Library, including some other checks. So it should work as expected now!
