### ISSUE TITLE
Using variables with a component

### ISSUE THREAD

**Issue by WichitaDude** [koenbok/Framer#521]
Is it possible to use a variable with a flow component?

**For example, I set a flow component:**
     flow = new FlowComponent
     flow.showNext(LayerA)

**Then set up a variable:**
     page = "LayerB"

**And then I submit it to a component like this:**
      ButtonA.onClick ->
      flow.showNext (page)

When I do this, I receive the error that it's expecting a layer name. I'm hoping that I'm just missing a bit of syntax. Suggestions...

**Comment by nvh** [comment]
Yes, but the variable you pass in should be a layer, not a string, so with `page = new Layer` this should work. 

Sidenote: The best place to ask these kind of programming questions is in our [Facebook group](http://framer.com/group) or through support@framer.com.

**Comment by WichitaDude** [comment]
Thanks for the advice and the tip on Facebook

Cheers,
andy
