### ISSUE TITLE
Ability to generate embed code for Adobe Portfolio

### ISSUE THREAD

**Issue by bhamlefty** [koenbok/Framer#523]
I understand you can ifame the Framer prototypes but many designers have portfolios hosted by site editors that don't allow you to edit the source code i.e Adobe Portfolio. I talked with them yesterday and they want to integrate with FramerJS but framer must first provide a embed code as they don't support iframe

**Comment by eelco** [comment]
I’m not directly familiar with Adobe Portfolio, but it seems they *do* use iframes for embedding (see https://help.myportfolio.com/hc/en-us/articles/215684818-What-Embed-Codes-do-you-support-) but have an explicit list of sources that are supported. If they would put framer.cloud on that list, it should work.
