### ISSUE TITLE
TextLayer performance

### ISSUE THREAD

**Issue by steveruizok** [koenbok/Framer#533]
Updating the content of a TextLayer is expensive, so much so that a system can redline when counters are updated on an interval. As I had one of those, I spent an hour digging around the inspector to try to find what was going wrong.

The culprit is getBoundingRects. It's called in StyledText.measure, which is in turn called [here](https://github.com/koenbok/Framer/blob/32df3a8e186bc4a406e1ee6dca140e38d933cacc/framer/TextLayer.coffee#L275) in TextLayer.renderText. Since this is called regardless of autoSize, setting explicit heights or widths doesn't improve performance. Performance can be improved by adding `if @autoSize` to line 275 and putting the rest into a block under it.

``` coffeescript
if @autoSize
	calculatedSize = @_styledText.measure constraints
	@disableAutosizeUpdating = true
	if calculatedSize.width?
		@width = calculatedSize.width + padding.left + padding.right
	if calculatedSize.height?
		@height = calculatedSize.height + padding.top + padding.bottom
	@disableAutosizeUpdating = false
```

A different solution I've found is to reinsert a set property into TextLayer.html (removed in the latest update) and make changes to the html property rather than the text property. This skips the render() function – and so long as a TextLayer began with some content in options.text, it will still set all styles correctly. 

```coffeescript
@define "html",
	get: ->
		@_elementHTML?.innerHTML or ""
	set: (html) ->
		@_elementHTML?.innerHTML = html
		@emit("change:text", html)
```

See [this example](https://framer.cloud/uRkPo) for comparisons. The performance differences are pretty significant. They are also much more pronounced in the Framer application, compared to the browser.

**Comment by steveruizok** [comment]
As an update, TextLayer still runs the expensive StyledText.measure function, even if a TextLayer is set to fixed height / width. This is greatly increasing render times for for prototypes with many text fields, or where many text fields are changing content. 

Adding a line like `return if not @autoSize` to the top of renderText fixes the issue. The function is expensive and shouldn't run if it isn't needed.

**Comment by nvh** [comment]
You're right. The actual condition for not autosizing was a bit more complicated, but it just landed in master
