### ISSUE TITLE
Framer Preview APP without WiFi

### ISSUE THREAD

**Issue by janwagner** [koenbok/Framer#539]
Hi,

is there a way of mirroring to my mobile (iOS) by cable? I am having connection issues over corporate wifi using the mirror feature.

If I open the "open in browser" preview on my mobile safari it works, but Framer Preview is not showing anything.

Thx Jan

**Comment by eelco** [comment]
Hi Jan, this is not directly supported by the app, but there is a way to makes this work, see: http://framergroup.com/posts/919753391485066.html I’ve also logged this as a feature request. I’m closing this issue, because it’s not directly related to the Framer Library.

**Comment by janwagner** [comment]
Thank you @eelco :) The link is helping a lot!
