### ISSUE TITLE
SF Pro font does not work in Framer iOS

### ISSUE THREAD

**Issue by maceuph** [koenbok/Framer#540]
I'm using iOS 11 beta and macOS 10.12.6. I installed the SF Pro font from Apple and set that as the font for my text layer in the Design tab. When I open my framer doc in Framer iOS, the font falls back to Times New Roman instead of SF Pro.  See attached sample project.
[SFProTest.framer.zip](https://github.com/koenbok/Framer/files/1249685/SFProTest.framer.zip)

**Comment by RayPS** [comment]
```coffeescript
layer.fontFamily = "-apple-system"
```
