### ISSUE TITLE
Layer onMouseOut Event Behavior

### ISSUE THREAD

**Issue by marija17** [koenbok/Framer#543]
In a scenario where I have a parent layer with a child layer contained inside it, the parent layer `onMouseOut` event is triggered every time the child layer is entered and left (note at no point is the parent layer being left).  This appears to be incorrect behavior to me.

As an example, here's some code that with a parent and child layer and onMouseOut events:
```
child = new Layer
	x: 50
	y: 50
	height: 100
	width: 100
	backgroundColor: "blue"

parent = new Layer
	height: 200
	width: 200
parent.addChild(child)

child.onMouseOut ->
	print "left child"
parent.onMouseOut ->
	print "left parent"
```
(BTW if I remove the `child.onMouseOut` event, the behavior is corrected, so it seems that child event could be related/the cause of the issue.)

**Comment by marija17** [comment]
Would someone be able to verify whether this is a bug or expected behavior?

**Comment by willricedesign** [comment]
I'd like to follow up on this, as it's been a huge pain point for complex prototypes that rely on mouse events. Is this intended behaviour?

**Comment by nvh** [comment]
This is the way the browser behaves, you're looking for different events called `mouseenter` and `mouseleave`:

```coffee
child.on "mouseenter", ->
	print "enter child"
parent.on "mouseenter", ->
	print "enter parent"
child.on "mouseleave", ->
	print "left child"
parent.on "mouseleave", ->
	print "left parent"
```

I'll check if I can add shorthands for these events as well
