### ISSUE TITLE
Voyage Forcing Unnecessary Upgrade

### ISSUE THREAD

**Issue by jhabdas** [koenbok/Framer#549]
https://framer.com/voyage/

This looks great. But I have to be honest, is there _really_ a good reason it cannot be used with a **paid version of Framer** purchased just over a year ago?

**Comment by nvh** [comment]
Well, in that year, we shipped [25 updates](https://framer.com/updates/) of Framer, including [Framer Design](https://framer.com/features/design/), which is used by Voyage. So actually, there's a pretty good reason that Voyage requires a recent version of Framer.

**Comment by jhabdas** [comment]
You're clearly been hauling. But the real concern here is that I paid more than $100 for a piece of software which is out of date in one year. That's a shame. I feel like I got robbed.
