### ISSUE TITLE
ambient light sensor bug on iPhone

### ISSUE THREAD

**Issue by domdewom** [koenbok/Framer#556]
I keep on having an issue with Framer Preview App on iOS and the iPhone's ambient light sensor. For some reason, as soon as my finger (accidentally) covers the light sensor at the top of the screen, the screen goes completely black... Turning off the Auto-Brightness feature (Settings->General->Accessibility->DisplayAccommodations) didn't change anything. I have tried it out now on multiple iPhones - everywhere the same. Any clue how I can solve this issue?

**Comment by nvh** [comment]
Hmmm, this is actually a side-effect of the feature that you can wave over your device to bring up the overlay. If you disable the "Wave over device" option in settings, this shouldn't happen anymore.
