### ISSUE TITLE
Weird behaviour on draggable element

### ISSUE THREAD

**Issue by Kiiiwiii** [koenbok/Framer#568]
- Framer version v102
- OS: OS X EI Capitan 10.11.6
- Problem description: element's animation can be stopped by click even when draggable is set to false.
- Expected behaviour: element's animation cannot be stopped

Code (just copy and paste to reproduce):
```
# Create the draggable layer
layer = new Layer
	x: Align.center
	y: 100
	backgroundColor: 'white'

# Enable dragging - ******* comment out the following two lines of codes to see another behaviour *******
layer.draggable.enabled = true
layer.draggable.enabled = false

# define an animation
animationA = new Animation layer,
	y: 700
	options:
		time:5
animationA.start()
```

**If you click on the layer during animation, the animation will be stoped. (even when I disable the drag)
However, if you comment out the draggable code, everything works fine**

SO... It seems like the animation of an element will be influenced if once I enabled the drag (even disable the drag after a while, this side effect will not disappear)

**Comment by nvh** [comment]
Good catch, just pushed a fix for this!
