### ISSUE TITLE
All the CodePen examples are broken

### ISSUE THREAD

**Issue by richardcornish** [koenbok/Framer#67]
The CodePen examples seem to link to either of these resources, which are both 404s now:

http://framerjs.com/static/js/framer.js
https://rawgit.com/koenbok/Framer/master/build/framer.js

I understand it's hard to find these CodePen authors to update their code, but if the pens can't be updated, then they should be removed from the website. It was quite the letdown to hear about v3, going straight to the examples, and getting nothing.

**Comment by dallasbpeters** [comment]
Any luck on publishing some new resources?

**Comment by richardcornish** [comment]
@dallasbpeters This issue was opened more than a year ago, and I think the website has gone through several revisions. I don't think any of the examples rely on CodePen anymore. 

http://framerjs.com/examples/

Were you thinking that other examples should exist?

@koenbok You should probably close this issue regardless.

**Comment by dallasbpeters** [comment]
Oh, I was thinking of a publicly hosted version of the framer.js so that we could make new Pens. :)

**Comment by nvh** [comment]
Another year has passed, and that publicly hosted version of framer.js is now at http://builds.framerjs.com

This issue deserves some closing.
