### ISSUE TITLE
Layer registration point vs originX/Y?

### ISSUE THREAD

**Issue by klebba** [koenbok/Framer#86]
The originX and originY properties are a bit confusing; I expected them to function as the registration point of the layer at first. Looking at how they are used with CSS transforms I now understand the difference, but I still want to affect the registration point of a layer for positioning purposes. This is what I'm talking about (Flash example) http://www.kirupa.com/developer/mx/rpoint.htm

Thanks!

**Comment by awt2542** [comment]
Here's a better example.
1. Click on layerA - state is correctly switched.
2. Click on layerA again - state doesn't go back to default (i.e not looping). Try "x" instead, and it will work.
```
layerA = new Layer
layerA.states.add goRight: midX: 200
layerA.on Events.Click, -> @states.next()
```
