### ISSUE TITLE
Animation delay resets animation to initial property

### ISSUE THREAD

**Issue by awt2542** [koenbok/Framer#89]
The delay property seems to ignore the current state of the layer it's animating. It always animates from the property it had when the method was first fired. I guess this is expected, but I'm not sure if it has any practical use? It feels a bit unintuitive. Here's an example of the resetting action (in this case resets to y:0 when the second animation kicks in) :

	imageLayer2 = new Layer x: 300

	imageLayer2.animate
		properties:
			y: 70

	imageLayer2.animate
		properties:
			y: 150
			opacity: 0.5
		delay: 0.5

And here's my workaround (or how I would prefer it to work). It continues from y=70:

	imageLayer = new Layer

	down = new Animation
		layer: imageLayer
		properties:
			y: 70

	moredown = new Animation
		layer: imageLayer
		properties:
			y: 150
			opacity: 0.5

	down.start()
	utils.delay(0.5, -> moredown.start())

**Comment by nvh** [comment]
This one is similar to #252, please add anything related to this there.
